### ISSUE TITLE
Kontribusi

### ISSUE THREAD

**Issue by anak10thn** [fedora-id/asknot-ng#9]
@ekoikhyar @sentabi @michel-slm untuk kontribusi selain menjadi menerjemah, apa saja yah? dan linknya :ghost:

**Comment by sentabi** [comment]
ada [FreeMedia](https://fedoraproject.org/wiki/Distribution/FreeMedia/Donation), [Mirrorring](https://fedoraproject.org/wiki/Infrastructure/Mirroring), [Ambassador ](https://fedoraproject.org/wiki/Ambassadors). 

lengkapnya ada disini [Join Fedora](https://fedoraproject.org/wiki/Join)

**Comment by ekoikhyar** [comment]
FreeMedia boleh sih dimasukkan, walau sdah jarang di pantau, sapa tau ada yg baru mau voluntier

**Comment by michel-slm** [comment]
oh mirroring boleh tuh, bagus idenya. FreeMedia .. iya juga buat yang di pelosok2 gitu ya. Kalau mau dimasukin mungkin halaman wikinya perlu kita terjemahkan juga.
